config.FixWidth = "";
config.StyleUploadDir = "../UploadFiles/";
config.InitMode = "EDIT";
config.AutoDetectPasteFromWord = "1";
config.BaseUrl = "1";
config.BaseHref = "";
config.AutoRemote = "1";
config.ShowBorder = "1";
config.StateFlag = "1";
config.SBCode = "1";
config.SBEdit = "1";
config.SBText = "1";
config.SBView = "1";
config.EnterMode = "1";
config.Skin =  "Office2003";
config.AutoDetectLanguage = "1";
config.DefaultLanguage = "zh-cn";
config.AllowBrowse = "1";
config.AllowImageSize = "200";
config.AllowFlashSize = "200";
config.AllowMediaSize = "200";
config.AllowFileSize = "500";
config.AllowRemoteSize = "300";
config.AllowLocalSize = "3";
config.AllowImageExt = "gif|jpg|jpeg|bmp|png";
config.AllowFlashExt = "swf";
config.AllowMediaExt = "rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov";
config.AllowFileExt = "rar|zip|pdf|doc|xls|ppt|chm|hlp";
config.AllowRemoteExt = "gif|jpg|bmp";
config.SYWZFlag = "3";
config.SYTPFlag = "3";
config.SLTFlag = "3";
config.ServerExt = "Asp";

config.Toolbars = [

["TBHandle","FormatBlock","FontName","FontSize","Cut","Copy","Paste","PasteText","PasteWord","Delete","RemoveFormat","TBSep","FindReplace","SpellCheck","TBSep","UnDo","ReDo","TBSep","SelectAll","UnSelect","TBSep","absolutePosition","zIndexBackward","zIndexForward"],
["TBHandle","Bold","Italic","UnderLine","StrikeThrough","SuperScript","SubScript","UpperCase","LowerCase","TBSep","JustifyLeft","JustifyCenter","JustifyRight","JustifyFull","TBSep","OrderedList","UnOrderedList","Indent","Outdent","TBSep","ForeColor","BackColor","TBSep","BgColor","BackImage","TBSep","Fieldset","Iframe","HorizontalRule","Marquee","TBSep","CreateLink","Anchor","Map","Unlink"],
["TBHandle","Image","Flash","Media","File","GalleryMenu","TBSep","TableMenu","FormMenu","TBSep","RemoteUpload","LocalUpload","ImportWord","ImportExcel","TBSep","BR","Paragraph","ParagraphAttr","TBSep","Template","Symbol","Emot","Art","NowDate","NowTime","Excel","Quote","TBSep","PrintBreak","Print","TBSep","ShowBorders","ZoomMenu","Maximize","About"]
];
